# Generated by Django 3.2.9 on 2021-11-22 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedulaCliente', models.CharField(max_length=30)),
                ('nombreCompletoCliente', models.CharField(max_length=30)),
                ('numeroCuenta', models.CharField(max_length=20)),
                ('montoCuenta', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montoTransferencia', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tipoTransferencia', models.CharField(max_length=30)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentasTransferencia', to='AustroAPI.cuenta')),
            ],
        ),
    ]
